task_id: UW-FrankaLeap-GraspBottle-IkRel-v0
checkpoint: logs/bc_cfm_pcd_grasp
obs_keys: [ee_pose, hand_joint_pos]
device: cuda:0
num_envs: 1
action_horizon: 1
num_warmup_steps: 5
spawn: cardinal_3x3
record_video: true
record_plots: true
